#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := a2dp_sink
EXTRA_COMPONENT_DIRS += $(PROJECT_PATH)/../../components


include $(IDF_PATH)/make/project.mk
include $(PROJECT_PATH)/../../make/deploy.mk

